apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  api_secret_key: {{ .Values.api_secret_key | b64enc }}
  saml_path: {{ .Values.saml_path | b64enc }}
  gateway_url: {{ .Values.gateway_url | b64enc }}
  session_cookie_domain: {{ .Values.session_cookie_domain | b64enc }}
  proxy_debug: {{ .Values.proxy_debug | b64enc }}
