## Override NGINX default Values
nginx:

  ## Autoscale container pods
  ##
  autoscaling:
    enabled: false
    minReplicas: "1"
    maxReplicas: "5"

  useStaticAssets: false


  ## @param serverBlock Custom server block to be added to NGINX configuration
  serverBlock: |-

        server {
          listen 8080;
          listen [::]:8080;
          server_name lsaapp.gww.gov.bc.ca;

          absolute_redirect off;

          error_page 401 403 = @login_required;

          # anyone with IDIR identity can access this
          location / {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;

            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_pass http://lsa-api-nginx;
          }

          # anyone can access this (requires token)
          location /api/attendees/rsvp {
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-api-nginx/api/attendees/rsvp;
          }

          # anyone with IDIR identity can access this
          location /registration/api/ {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-registration-node:3001/;
          }

          # anyone with IDIR identity can access this
          location /registration/ {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-registration-node:3000/;
          }

          # anyone with IDIR identity can access this
          location /registration/rsvp {
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-registration-node:3000/rsvp;
          }

          # anyone with IDIR identity can access this
          location /registration/js {
            proxy_pass_header Content-Type;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-registration-node:3000/js;
          }

          # anyone can access this
          location /registration/css {
            proxy_pass_header Content-Type;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-registration-node:3000/css;
          }

          # anyone with IDIR identity can access this
          location /registration/img {
            proxy_pass_header Content-Type;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-registration-node:3000/img;
          }

          # anyone can access this
          location /admin/ {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://lsa-admin-node:3000/;
          }

          # anyone with IDIR identity can access this
          location /service-pins-spring-2022/ {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://servicepins-servicepinpdfgenerator:8000/;
          }

          location /auth/ {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Host lsaapp.gww.gov.bc.ca;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
            proxy_pass http://proxy-gateway-flask:8000/;
          }

          location /sso {
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://proxy-gateway-flask:8000/sso;
          }

          location /acs {
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://proxy-gateway-flask:8000/acs;
          }

          location /slo {
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://proxy-gateway-flask:8000/slo;
          }

          location /user_info {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://proxy-gateway-flask:8000/user;
          }

          location @login_required {
            return 302 https://lsaapp.gww.gov.bc.ca/sso?relay=$request_uri;
          }


        }
